"""Model provider adapters."""

from .base import (
    LLMProvider,
    LLMResponse,
    ProviderConfigurationError,
    ProviderError,
    ProviderResponseError,
    ProviderUnavailableError,
    ToolCall,
)
from .deepseek import DeepSeekProvider
from .anthropic import (
    AnthropicCompatibleProvider,
    inspect_anthropic_endpoint,
    normalize_anthropic_response,
    parse_anthropic_models_payload,
    to_anthropic_request_payload,
)
from .agent_audit_adapter import (
    AGENT_AUDIT_ADAPTER_COMPLETIONS_PATH,
    AGENT_AUDIT_ADAPTER_MANIFEST_PATH,
    AGENT_AUDIT_ADAPTER_MAX_TOKENS,
    AGENT_AUDIT_ADAPTER_MODELS_PATH,
    AGENT_AUDIT_ADAPTER_PROTOCOL_VERSION,
    AgentAuditAdapterCapabilities,
    AgentAuditAdapterInspectionError,
    AgentAuditAdapterManifest,
    AgentAuditAdapterProvider,
    CanonicalCompletionRequest,
    CanonicalCompletionResponse,
    CanonicalMessage,
    CanonicalToolCall,
    CanonicalToolDefinition,
    CanonicalUsage,
    ProviderCapabilityManifest,
    inspect_agent_audit_adapter_endpoint,
    parse_agent_audit_adapter_manifest,
)
from .ollama import OllamaProvider
from .openai_compatible import OpenAICompatibleProvider
from .runtime import PROVIDER_CREDENTIAL_ENV, create_runtime_provider

__all__ = [
    "DeepSeekProvider",
    "AnthropicCompatibleProvider",
    "AgentAuditAdapterProvider",
    "AgentAuditAdapterCapabilities",
    "AgentAuditAdapterInspectionError",
    "AgentAuditAdapterManifest",
    "ProviderCapabilityManifest",
    "inspect_agent_audit_adapter_endpoint",
    "parse_agent_audit_adapter_manifest",
    "inspect_anthropic_endpoint",
    "normalize_anthropic_response",
    "parse_anthropic_models_payload",
    "to_anthropic_request_payload",
    "CanonicalCompletionRequest",
    "CanonicalCompletionResponse",
    "CanonicalMessage",
    "CanonicalToolCall",
    "CanonicalToolDefinition",
    "CanonicalUsage",
    "AGENT_AUDIT_ADAPTER_PROTOCOL_VERSION",
    "AGENT_AUDIT_ADAPTER_MANIFEST_PATH",
    "AGENT_AUDIT_ADAPTER_MODELS_PATH",
    "AGENT_AUDIT_ADAPTER_COMPLETIONS_PATH",
    "AGENT_AUDIT_ADAPTER_MAX_TOKENS",
    "LLMProvider",
    "LLMResponse",
    "OllamaProvider",
    "OpenAICompatibleProvider",
    "PROVIDER_CREDENTIAL_ENV",
    "ProviderConfigurationError",
    "ProviderError",
    "ProviderResponseError",
    "ProviderUnavailableError",
    "ToolCall",
    "create_runtime_provider",
]
